/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.c" instead.
 */

#include <check.h>

#line 1 "test.c"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <check.h>
#include "string.h"
void change (int *a)
{
	(*a)++;
}

// int main(void)
// {
// 	// int a = 10123;
// 	// char str[80] = {};
// 	// char *xmp;
// 	// xmp = (char *)malloc(sizeof(char) * 5);
// 	// char *p = xmp;
// 	// // change(&a);'
// 	// for (int i = 0; a > 0; i++)
// 	// {

// 	// 	xmp[i] = (a % 10) + 48;
// 	// 	a = a / 10;
// 	// 	// xmp++;
// 	// }
// 	// a = a / 10;
// 	// xmp[3] = (a % 10) + 48;
// 	// xmp[4] = '\0';
// 	//  int a = 1234567123;
// 	// float a = 10.123;
// 	// char str[80] = {};
// 	// int tmp = 0;
// 	// for (int i = 0; i < 6; i++)
// 	// {
// 	// 	tmp = (int)a;
// 	// 	for (int j = i; tmp > 0; j++)
// 	// 	{
// 	// 		str[j] = tmp % 10 + '0';
// 	// 		tmp /= 10;
// 	// 	}
// 	// 	a -= (int)a;
// 	// 	a *= 10;
// 	// }
// 	printf("%u\n", 10);
// 	return 0;
// }
// int main()
// {
//     START_TEST (test_is_digit)
//     {
//         ck_assert_str_eq(is_digit('a'), 0);
//     }
//     END_TEST
//     return 0;
// }
START_TEST(isdigittest)
{
#line 57
    fail_unless(is_digit('a') == 0, "blal");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, isdigittest);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
